/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from "react";
import * as THREE from "three";
import { useGLTF, useMask } from "@react-three/drei";
import { useShirtSectionTextures } from "@/src/lib/useTextures";
import { createMaterials } from "@/src/lib/material";
import type { TextureKey } from "@/src/lib/textures";
import Masking from "./Masking";
import useAnimation from "@/src/lib/useAnimation";

type GLTFResult = GLTF & { nodes: { [name: string]: THREE.Mesh } };
function FirstWhiteModel() {
  const { nodes } = useGLTF(
    "/models/white/WhiteStudio.glb",
  ) as unknown as GLTFResult;

  const stencil = useMask(1);
  const groupRef = useRef<THREE.Group>(null);
  const shirtRef = useRef<THREE.Mesh>(null);
  const maskRef = useRef<THREE.Mesh>(null);

  const textures = useShirtSectionTextures("white", "first");
  const materials = createMaterials(textures, stencil) as Record<
    TextureKey<"white", "first">,
    THREE.MeshBasicMaterial
  >;

  useAnimation(groupRef, shirtRef, maskRef);
  return (
    <group>
      <Masking ref={maskRef} />
      <group ref={groupRef} dispose={null}>
        <mesh geometry={nodes.DJ_Table.geometry} material={materials.dj} />
        <mesh
          geometry={nodes.Speakers.geometry}
          material={materials.speakers}
        />
        <mesh
          geometry={nodes.LED_Cube_White.geometry}
          material={materials.studio}
        />
        <mesh
          ref={shirtRef}
          geometry={nodes.Shirt_White.geometry}
          position={[0, 0.7, 0]}
          material={materials.shirt}
        />
        <mesh geometry={nodes.Wall.geometry} material={materials.studio} />
        <mesh geometry={nodes.Floor.geometry} material={materials.studio} />
        <mesh geometry={nodes.TV.geometry} material={materials.tv} />
        <mesh geometry={nodes.TV_Screen.geometry} material={materials.tv} />
      </group>
    </group>
  );
}

useGLTF.preload("/models/white/WhiteStudio.glb");

export default FirstWhiteModel;
