/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { useShirtSectionTextures } from "@/src/lib/useTextures";
import { createMaterials } from "@/src/lib/material";
import type { TextureKey } from "@/src/lib/textures";

type GLTFResult = GLTF & { nodes: { [name: string]: THREE.Mesh } };
function FirstGrayModel() {
  const { nodes } = useGLTF(
    "/models/gray/GrayStudio.glb",
  ) as unknown as GLTFResult;

  const textures = useShirtSectionTextures("gray", "first");
  const materials = createMaterials(textures) as Record<
    TextureKey<"gray", "first">,
    THREE.MeshBasicMaterial
  >;

  console.log("materials gray first", materials);
  return (
    <group dispose={null}>
      <mesh
        geometry={nodes.Shirt_Gray.geometry}
        material={materials.shirt}
        position={[0, 0.7, 0]}
      />
      <mesh geometry={nodes.Floor.geometry} material={materials.floor} />
      <mesh geometry={nodes.Wall.geometry} material={materials.wall} />
      <mesh geometry={nodes.Asset.geometry} material={materials.assets} />
    </group>
  );
}

useGLTF.preload("/models/gray/GrayStudio.glb");

export default FirstGrayModel;
