/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { useShirtSectionTextures } from "@/src/lib/useTextures";
import { createMaterials } from "@/src/lib/material";
import type { TextureKey } from "@/src/lib/textures";

type GLTFResult = GLTF & { nodes: { [name: string]: THREE.Mesh } };
function FirstWhiteModel() {
  const { nodes } = useGLTF(
    "/models/white/WhiteStudio.glb",
  ) as unknown as GLTFResult;

  const textures = useShirtSectionTextures("white", "first");
  const materials = createMaterials(textures) as Record<
    TextureKey<"white", "first">,
    THREE.MeshBasicMaterial
  >;
  return (
    <group dispose={null}>
      <mesh geometry={nodes.DJ_Table.geometry} material={materials.dj} />
      <mesh geometry={nodes.Speakers.geometry} material={materials.speakers} />
      <mesh
        geometry={nodes.LED_Cube_White.geometry}
        material={materials.studio}
      />
      <mesh
        geometry={nodes.Shirt_White.geometry}
        position={[0, 0.7, 0]}
        material={materials.shirt}
      />
      <mesh geometry={nodes.Wall.geometry} material={materials.studio} />
      <mesh geometry={nodes.Floor.geometry} material={materials.studio} />
      <mesh geometry={nodes.TV.geometry} material={materials.tv} />
      <mesh geometry={nodes.TV_Screen.geometry} material={materials.tv} />
    </group>
  );
}

useGLTF.preload("/models/white/WhiteStudio.glb");

export default FirstWhiteModel;
