/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import { useRef } from "react";
import { useGLTF, useMask } from "@react-three/drei";
import { useShirtSectionTextures } from "@/src/lib/useTextures";
import { createMaterials } from "@/src/lib/material";
import type { TextureKey } from "@/src/lib/textures";
import useAnimation from "@/src/lib/useAnimation";
import Masking from "./Masking";

type GLTFResult = GLTF & { nodes: { [name: string]: THREE.Mesh } };
function FirstSportModel() {
  const { nodes } = useGLTF(
    "/models/sport/SportStudio.glb",
  ) as unknown as GLTFResult;

  const stencil = useMask(1);
  const shirtRef = useRef<THREE.Mesh>(null);
  const groupRef = useRef<THREE.Group>(null);
  const maskRef = useRef<THREE.Mesh>(null);

  const textures = useShirtSectionTextures("sport", "first");
  const materials = createMaterials(textures, stencil) as Record<
    TextureKey<"sport", "first">,
    THREE.MeshBasicMaterial
  >;

  useAnimation(groupRef, shirtRef, maskRef);

  console.log("materials sport first", materials);
  return (
    <group>
      <Masking ref={maskRef} />
      <group ref={groupRef} dispose={null}>
        <mesh
          ref={shirtRef}
          geometry={nodes.Shirt_Sport.geometry}
          material={materials.shirt}
          position={[0, 0.7, 0]}
          rotation={[Math.PI, 0, Math.PI]}
        />
        <mesh geometry={nodes.Environment.geometry} material={materials.env} />
        <mesh geometry={nodes.Ramp.geometry} material={materials.ramp} />
        <mesh
          geometry={nodes.SakteBoard.geometry}
          material={materials.skateboard}
          position={[0, -0.012, 0]}
        />
      </group>
    </group>
  );
}

export default FirstSportModel;
