/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
"use client";

import { useRef } from "react";
import * as THREE from "three";
import { useGLTF, useMask } from "@react-three/drei";
import useAnimation from "@/src/lib/useAnimation";
import { useShirtSectionTextures } from "@/src/lib/useTextures";
import { createMaterials } from "@/src/lib/material";
import Masking from "./Masking";

import type { TextureKey } from "@/src/lib/textures";
import type { GLTF } from "three-stdlib";

type GLTFResult = GLTF & { nodes: { [name: string]: THREE.Mesh } };
function FirstGrayModel() {
  const { nodes } = useGLTF(
    "/models/gray/GrayStudio.glb",
  ) as unknown as GLTFResult;

  const stencil = useMask(1);
  const maskRef = useRef<THREE.Mesh>(null);
  const groupRef = useRef<THREE.Group>(null);

  const shirtRef = useRef<THREE.Mesh>(null);

  const textures = useShirtSectionTextures("gray", "first");
  if (!textures) return;
  const materials = createMaterials(textures, stencil) as Record<
    TextureKey<"gray", "first">,
    THREE.MeshBasicMaterial
  >;

  useAnimation(groupRef, shirtRef, maskRef);
  return (
    <group>
      <Masking ref={maskRef} />
      <group ref={groupRef} dispose={null}>
        <mesh
          ref={shirtRef}
          geometry={nodes.Shirt_Gray.geometry}
          material={materials.shirt}
          position={[0, 0.7, 0]}
        />
        <mesh geometry={nodes.Floor.geometry} material={materials.floor} />
        <mesh geometry={nodes.Wall.geometry} material={materials.wall} />
        <mesh geometry={nodes.Asset.geometry} material={materials.assets} />
      </group>
    </group>
  );
}

export default FirstGrayModel;
