/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { useGSAP } from "@gsap/react";
import gsap from "gsap";
import { useShirtSectionTextures } from "@/src/lib/useTextures";
import { createMaterials } from "@/src/lib/material";
import type { ShirtType } from "@/src/lib/textures";
import type { TextureKey } from "@/src/lib/textures";
import { shirtTextColors } from "@/src/lib/colors";
import { useResponsive } from "@/src/store/useResponsive";

type GLTFResult = GLTF & { nodes: { [name: string]: THREE.Mesh } };

export function SecondModel({ shirtType }: { shirtType: ShirtType }) {
  const { nodes } = useGLTF(
    "/models/ShirtScrolling.glb",
  ) as unknown as GLTFResult;

  const { isMobile } = useResponsive();

  console.log("nodes:", nodes);

  const textures = useShirtSectionTextures(shirtType, "second");
  const materials = createMaterials(textures) as Record<
    TextureKey<typeof shirtType, "second">,
    THREE.MeshBasicMaterial
  >;

  const getTextColor = () => shirtTextColors[shirtType].text || 0x000000;

  const textsMaterial = new THREE.MeshBasicMaterial({
    color: getTextColor(),
    transparent: true,
    opacity: 1,
  });

  const marqueeMaterial = new THREE.MeshBasicMaterial({
    color: getTextColor(),
    transparent: true,
    opacity: 1,
  });

  const TOP_BOTTOM_TEXT_WIDTH = 5.7;
  const MIDDLE_TEXT_WIDTH = 6.2;
  const DURATION = 50;

  const marqueeText1Ref = useRef<THREE.Mesh>(null);
  const marqueeText1DupRef = useRef<THREE.Mesh>(null);
  const marqueeText2Ref = useRef<THREE.Mesh>(null);
  const marqueeText2DupRef = useRef<THREE.Mesh>(null);

  useGSAP(() => {
    if (
      !marqueeText1Ref.current ||
      !marqueeText1DupRef.current ||
      !marqueeText2Ref.current ||
      !marqueeText2DupRef.current
    )
      return;

    gsap.to(
      [marqueeText1Ref.current.position, marqueeText1DupRef.current.position],
      {
        x: `-=${TOP_BOTTOM_TEXT_WIDTH}`,
        duration: DURATION,
        ease: "none",
        repeat: -1,
      },
    );

    gsap.to(
      [marqueeText2Ref.current.position, marqueeText2DupRef.current.position],
      {
        x: `+=${MIDDLE_TEXT_WIDTH}`,
        duration: DURATION,
        ease: "none",
        repeat: -1,
      },
    );
  }, []);

  return (
    <group dispose={null} scale={isMobile ? 1.4 : 2.2}>
      <mesh geometry={nodes.Shirt.geometry} material={materials.shirt} />
      <mesh geometry={nodes.Sphere_ENV.geometry} material={materials.sphere} />
      <group>
        {Object.entries(nodes)
          .filter(([key]) => key.startsWith("Texts"))
          .map(([key, node]) => (
            <mesh
              key={key}
              position={node.position}
              geometry={node.geometry}
              material={textsMaterial}
            />
          ))}
      </group>
      <mesh
        ref={marqueeText1Ref}
        geometry={nodes.Marquee_Top_Bottom.geometry}
        material={marqueeMaterial}
        position={[0, 0, 0]}
      />

      <mesh
        ref={marqueeText1DupRef}
        geometry={nodes.Marquee_Top_Bottom.geometry}
        material={marqueeMaterial}
        position={[TOP_BOTTOM_TEXT_WIDTH, 0, 0]}
      />
      <mesh
        ref={marqueeText2Ref}
        geometry={nodes.Marquee_Middle.geometry}
        material={marqueeMaterial}
        position={[0, 0, 0]}
      />
      <mesh
        ref={marqueeText2DupRef}
        geometry={nodes.Marquee_Middle.geometry}
        material={marqueeMaterial}
        position={[-MIDDLE_TEXT_WIDTH, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/models/ShirtScrolling.glb");
