/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
"use client";

import { useRef, useMemo, RefObject } from "react";
import * as THREE from "three";
import { useGLTF, useMask } from "@react-three/drei";
import { useGSAP } from "@gsap/react";
import gsap from "gsap";
import { useShirtSectionTextures } from "@/src/lib/useTextures";
import { createMaterials } from "@/src/lib/material";
import type { ShirtType } from "@/src/lib/textures";
import type { TextureKey } from "@/src/lib/textures";
import type { GLTF } from "three-stdlib";
import { shirtTextColors } from "@/src/lib/colors";
import { useResponsive } from "@/src/store/useResponsive";

type GLTFResult = GLTF & { nodes: { [name: string]: THREE.Mesh } };

function SecondModel({ shirtType }: { shirtType: ShirtType }) {
  const { nodes } = useGLTF(
    "/models/ShirtScrolling.glb",
  ) as unknown as GLTFResult;

  const stencil = useMask(1, true);

  const { isMobile } = useResponsive();

  console.log("nodes:", nodes);

  const textures = useShirtSectionTextures(shirtType, "second");
  if (!textures) return;
  const materials = createMaterials(textures, stencil) as Record<
    TextureKey<typeof shirtType, "second">,
    THREE.MeshBasicMaterial
  >;

  const getTextColor = () => shirtTextColors[shirtType].text || 0x000000;

  const textsMaterial = useMemo(() => {
    return new THREE.MeshBasicMaterial({
      color: getTextColor(),
      transparent: true,
      opacity: 1,
      ...stencil,
    });
  }, [getTextColor, stencil]);

  const marqueeMaterial = useMemo(() => {
    return new THREE.MeshBasicMaterial({
      color: getTextColor(),
      transparent: true,
      opacity: 0,
      ...stencil,
    });
  }, [getTextColor, stencil]);

  const TOP_BOTTOM_TEXT_WIDTH = 5.7;
  const MIDDLE_TEXT_WIDTH = 6.2;
  const DURATION = 50;

  const marqueeText1Ref = useRef<THREE.Mesh>(null);
  const marqueeText1DupRef = useRef<THREE.Mesh>(null);
  const marqueeText2Ref = useRef<THREE.Mesh>(null);
  const marqueeText2DupRef = useRef<THREE.Mesh>(null);

  const groupRef = useRef<THREE.Group>(null);
  const textsRef = useRef<THREE.Group>(null);

  const animateTexts = (textsRef: RefObject<THREE.Group | null>) => {
    const tl = gsap.timeline();
    const group = textsRef.current;
    if (!group) return tl;

    (group.children as THREE.Mesh[]).forEach((mesh, i) => {
      tl.from(
        mesh.scale,
        { x: 0, y: 0, z: 0, duration: 1.5, ease: "back.inOut" },
        i * 0.2,
      );
      tl.from(
        mesh.position,
        { y: "+=0.04", duration: 1.5, ease: "back.out" },
        i * 0.2,
      );
    });

    return tl;
  };

  useGSAP(() => {
    if (
      !marqueeText1Ref.current ||
      !marqueeText1DupRef.current ||
      !marqueeText2Ref.current ||
      !marqueeText2DupRef.current
    )
      return;

    gsap.to(
      [marqueeText1Ref.current.position, marqueeText1DupRef.current.position],
      {
        x: `-=${TOP_BOTTOM_TEXT_WIDTH}`,
        duration: DURATION,
        ease: "none",
        repeat: -1,
      },
    );

    gsap.to(
      [marqueeText2Ref.current.position, marqueeText2DupRef.current.position],
      {
        x: `+=${MIDDLE_TEXT_WIDTH}`,
        duration: DURATION,
        ease: "none",
        repeat: -1,
      },
    );
  }, []);

  useGSAP(() => {
    if (!groupRef.current) return;
    const tl = gsap.timeline({
      scrollTrigger: {
        trigger: "#second-section",
        start: "top top",
        end: "bottom top",
        toggleActions: "restart reverse restart reverse",
        scrub: 1,
        pin: true,
        // markers: true,
      },
    });
    tl.to(groupRef.current.rotation, { x: 0, duration: 0.2 })
      .to(groupRef.current.position, { y: 0.7, duration: 0.8 }, "<")
      .to(groupRef.current.rotation, { y: -Math.PI * 2, duration: 0.8 }, "<")
      .to(groupRef.current.scale, { x: 1, y: 1, z: 1, duration: 0.1 })
      .to(textsMaterial, { opacity: 0, duration: 0.05 }, "<")
      .to(marqueeMaterial, { opacity: 0.2, duration: 0.05 }, "<")
      .to(groupRef.current.position, { y: 0.7 })
      .add(animateTexts(textsRef).duration(0.5), 0);
  }, []);

  return (
    <group
      ref={groupRef}
      dispose={null}
      scale={isMobile ? 1.4 : 2.2}
      rotation={[Math.PI / 8, Math.PI / 3, 0]}
      position-y={0.1}
    >
      <mesh geometry={nodes.Shirt.geometry} material={materials.shirt} />
      <mesh geometry={nodes.Sphere_ENV.geometry} material={materials.sphere} />
      <group ref={textsRef}>
        {Object.entries(nodes)
          .filter(([key]) => key.startsWith("Texts"))
          .map(([key, node]) => (
            <mesh
              key={key}
              position={node.position}
              geometry={node.geometry}
              material={textsMaterial}
            />
          ))}
      </group>
      <mesh
        ref={marqueeText1Ref}
        geometry={nodes.Marquee_Top_Bottom.geometry}
        material={marqueeMaterial}
        position={[0, 0, 0]}
      />

      <mesh
        ref={marqueeText1DupRef}
        geometry={nodes.Marquee_Top_Bottom.geometry}
        material={marqueeMaterial}
        position={[TOP_BOTTOM_TEXT_WIDTH, 0, 0]}
      />
      <mesh
        ref={marqueeText2Ref}
        geometry={nodes.Marquee_Middle.geometry}
        material={marqueeMaterial}
        position={[0, 0, 0]}
      />
      <mesh
        ref={marqueeText2DupRef}
        geometry={nodes.Marquee_Middle.geometry}
        material={marqueeMaterial}
        position={[-MIDDLE_TEXT_WIDTH, 0, 0]}
      />
    </group>
  );
}

export default SecondModel;
