/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

"use client";

import { useRef, useEffect, useCallback, useMemo } from "react";
import { useRouter } from "next/navigation";
import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import gsap from "gsap";
import { useGSAP } from "@gsap/react";

import { useStore } from "../store/useStore";
import { useResponsive } from "../store/useResponsive";

import { useMainStudioTextures } from "../lib/useTextures";
import { createMaterials } from "../lib/material";

import type { GLTF } from "three-stdlib";
import type { StudioMaterial } from "../store/useStore";

type GLTFResult = GLTF & {
  nodes: { [name: string]: THREE.Mesh };
};
type ShirtSlug = "white" | "gray" | "sport";

interface ShirtConfig {
  slug: ShirtSlug;
  geometry: THREE.BufferGeometry;
  position: [number, number, number];
  rotation: [number, number, number];
  material: THREE.Material;
  hoverMat: StudioMaterial;
}

// Definido fuera del componente — no se recrea en cada render
const SHIRT_POSITIONS: [number, number, number][] = [
  [0.65, 0.7, -0.45],
  [-0.65, 0.7, -0.45],
  [0, 0.7, 0],
];

const MOBILE_OFFSET = 0.65;

function MainStudioModel() {
  const { nodes } = useGLTF(
    "/models/main/MainStudio.glb",
  ) as unknown as GLTFResult;

  const textures = useMainStudioTextures();
  if (!textures) return null;
  const materials = createMaterials(textures);

  const {
    defaultStudio,
    whiteStudio,
    redStudio,
    grayStudio,
    sportShirt,
    whiteShirt,
    grayShirt,
  } = materials;

  const studioMaterials = {
    defaultStudio,
    whiteStudio,
    redStudio,
    grayStudio,
  };

  // Memorizar shirts config — evita recrear el array en cada render
  const shirts = useMemo<ShirtConfig[]>(
    () => [
      {
        slug: "white",
        geometry: nodes.Shirt_White.geometry,
        position: SHIRT_POSITIONS[0],
        rotation: [0, Math.PI, 0],
        material: whiteShirt,
        hoverMat: "whiteStudio",
      },
      {
        slug: "gray",
        geometry: nodes.Shirt_Sport.geometry,
        position: SHIRT_POSITIONS[1],
        rotation: [0, Math.PI, 0],
        material: grayShirt,
        hoverMat: "grayStudio",
      },
      {
        slug: "sport",
        geometry: nodes.Shirt_Gray.geometry,
        position: SHIRT_POSITIONS[2],
        rotation: [0, Math.PI, 0],
        material: sportShirt,
        hoverMat: "redStudio",
      },
    ],
    [nodes, materials],
  );

  const activeStudioMaterial = useStore((state) => state.activeStudioMaterial);
  const setStudioMaterial = useStore((state) => state.setStudioMaterial);
  const currentIndex = useStore((state) => state.currentIndex);

  const scale = useResponsive((state) => state.scale);
  console.log("Scale from store:", scale);

  const groupRef = useRef<THREE.Group>(null);
  const meshRefs = useRef<(THREE.Mesh | null)[]>([]);
  const tlRefs = useRef<(GSAPTimeline | null)[]>([]);

  const router = useRouter();

  // Prefetch en mount — sin deps innecesarias
  useEffect(() => {
    // isMobile.current = window.innerWidth <= 768;
    shirts.forEach(({ slug }) => router.prefetch(`/shirts/${slug}`));
  }, [shirts, router]);

  useGSAP(() => {
    const hasAnimationRun = sessionStorage.getItem("mainStudioAnimationRan");
    if (!groupRef.current || hasAnimationRun) return;
    gsap.from(groupRef.current.position, {
      y: -0.15,
      z: 2,
      duration: 4,
      ease: "power4.inOut",
      onComplete: () => {
        sessionStorage.setItem("mainStudioAnimationRan", "true");
      },
    });
    meshRefs.current.forEach((shirt, i) => {
      if (!shirt) return;
      gsap.from(shirt.position, {
        x: shirt.position.x * 2,
        delay: 1,
        duration: 3,
        ease: "power2.inOut",
      });
      gsap.from(shirt.rotation, {
        y: shirt.rotation.y * 4,
        delay: 1,
        duration: 3,
        ease: "power2.out",
      });
    });
  });
  // Un solo useGSAP para crear las timelines — depende de nodes (estables post-load)
  useGSAP(
    () => {
      meshRefs.current.forEach((mesh, idx) => {
        if (!mesh) return;

        // Limpiar timeline previa si existe
        tlRefs.current[idx]?.kill();

        tlRefs.current[idx] = gsap
          .timeline({ paused: true })
          .to(mesh.rotation, { y: 0, duration: 1, ease: "power2.inOut" })
          .to(
            mesh.scale,
            { x: 1.05, y: 1.05, z: 1.05, duration: 1, ease: "power2.inOut" },
            "<",
          );
      });

      // Cleanup al desmontar
      return () => tlRefs.current.forEach((tl) => tl?.kill());
    },
    { dependencies: [] }, // Solo se ejecuta una vez tras el mount
  );

  // Mobile carousel — usando gsap.to directamente, más eficiente que iterar todos
  useGSAP(() => {
    for (let i = 0; i < meshRefs.current.length; i++) {
      const mesh = meshRefs.current[i];
      if (!mesh) continue;
      switch (currentIndex) {
        case 0:
          gsap.to(mesh.position, { x: mesh.position.x - 0.65 });
          gsap.to(mesh.rotation, { y: 0 });
          gsap.to(meshRefs.current[0]!.position, { z: 0 });
          gsap.to(meshRefs.current[1]!.position, { z: -0.45 });
          setStudioMaterial("whiteStudio");
          break;
        case 1:
          gsap.to(mesh.position, {
            x: shirts[i].position[0],
            z: shirts[i].position[2],
          }); // Volver a posición original
          setStudioMaterial("redStudio");
          break;
        case 2:
          gsap.to(mesh.position, { x: mesh.position.x + 0.65 });
          gsap.to(mesh.rotation, { y: 0 });
          gsap.to(meshRefs.current[2]!.position, { z: 0 });
          gsap.to(meshRefs.current[1]!.position, { z: -0.45 });
          setStudioMaterial("grayStudio");
          break;
      }
    }
  }, [currentIndex]);

  // useCallback para evitar recrear handlers en cada render
  const enterHandler = useCallback((idx: number, hoverMat: StudioMaterial) => {
    document.body.style.cursor = "pointer";
    setStudioMaterial(hoverMat);
    tlRefs.current[idx]?.play();
  }, []);

  const leaveHandler = useCallback((idx: number) => {
    document.body.style.cursor = "auto";
    setStudioMaterial("defaultStudio");
    tlRefs.current[idx]?.reverse();
  }, []);

  const handleClick = useCallback((slug: string) => {
    router.push(`/shirts/${slug}`);
  }, []);

  return (
    <group ref={groupRef} dispose={null} scale={scale}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Environment.geometry}
        material={studioMaterials[activeStudioMaterial]}
      />

      {shirts.map((shirt, idx) => (
        <mesh
          ref={(el) => {
            meshRefs.current[idx] = el;
          }}
          key={shirt.slug} // key estable (slug) en lugar de idx
          geometry={shirt.geometry}
          position={shirt.position}
          rotation={shirt.rotation}
          material={shirt.material}
          onPointerEnter={() => enterHandler(idx, shirt["hoverMat"])}
          onPointerLeave={() => leaveHandler(idx)}
          onClick={() => handleClick(shirt.slug)}
        />
      ))}

      <mesh
        geometry={nodes.Hitbox.geometry}
        scale={[2.52, 1, 1]}
        visible={false}
        onPointerLeave={() => setStudioMaterial("defaultStudio")}
      />
    </group>
  );
}

export default MainStudioModel;
