/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
"use client";

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

import { useMainStudioTextures } from "../lib/useTextures";
import { createMaterials } from "../lib/material";

type GLTFResult = GLTF & {
  nodes: {
    [name: string]: THREE.Mesh;
  };
};

function MainStudioModel() {
  const { nodes } = useGLTF(
    "/models/main/MainStudio.glb",
  ) as unknown as GLTFResult;

  const textures = useMainStudioTextures();
  const materials = createMaterials(textures);

  const {
    defaultStudio,
    whiteStudio,
    redStudio,
    grayStudio,
    sportShirt,
    whiteShirt,
    grayShirt,
  } = materials;

  console.log("materials", materials);

  return (
    <group dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Environment.geometry}
        material={defaultStudio}
      />
      <mesh
        geometry={nodes.Shirt_White.geometry}
        position={[0.65, 0.7, -0.45]}
        rotation={[0, Math.PI / 9, 0]}
        material={whiteShirt}
      />
      <mesh
        geometry={nodes.Shirt_Sport.geometry}
        position={[0, 0.7, 0]}
        rotation={[0, -Math.PI, 0]}
        material={grayShirt}
      />
      <mesh
        geometry={nodes.Shirt_Gray.geometry}
        position={[-0.65, 0.7, -0.45]}
        rotation={[0, -Math.PI / 9, 0]}
        material={sportShirt}
      />
      <mesh
        geometry={nodes.Hitbox.geometry}
        scale={[2.52, 1, 1]}
        visible={false}
      />
    </group>
  );
}

useGLTF.preload("/models/main/MainStudio.glb");

export default MainStudioModel;
