/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

"use client";

import { useRef, useEffect, useCallback } from "react";
import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useGSAP } from "@gsap/react";
import { useRouter } from "next/navigation";
import gsap from "gsap";

import { useMainStudioTextures } from "../lib/useTextures";
import { createMaterials } from "../lib/material";
import { studioTextures } from "../lib/textures";
import { useStore } from "../store/useStore";
import { useResponsive } from "../store/useResponsive";

type GLTFResult = GLTF & { nodes: { [name: string]: THREE.Mesh } };
type ShirtSlug = "white" | "gray" | "sport";

interface ShirtConfig {
  slug: ShirtSlug;
  geometry: THREE.BufferGeometry;
  position: [number, number, number];
  rotation: [number, number, number];
  material: THREE.Material;
  hoverMat: THREE.Material;
}

// Definido fuera del componente — no se recrea en cada render
const SHIRT_POSITIONS: [number, number, number][] = [
  [0.65, 0.7, -0.45],
  [-0.65, 0.7, -0.45],
  [0, 0.7, 0],
];

const MOBILE_OFFSET = 0.65;

function MainStudioModel() {
  const { nodes } = useGLTF(
    "/models/main/MainStudio.glb",
  ) as unknown as GLTFResult;

  const textures = useMainStudioTextures();
  const materials = createMaterials(textures);

  const {
    defaultStudio,
    whiteStudio,
    redStudio,
    grayStudio,
    sportShirt,
    whiteShirt,
    grayShirt,
  } = materials;

  // Memorizar shirts config — evita recrear el array en cada render
  const shirts = useRef<ShirtConfig[]>([
    {
      slug: "white",
      geometry: nodes.Shirt_White.geometry,
      position: SHIRT_POSITIONS[0],
      rotation: [0, Math.PI, 0],
      material: whiteShirt,
      hoverMat: whiteStudio,
    },
    {
      slug: "gray",
      geometry: nodes.Shirt_Sport.geometry,
      position: SHIRT_POSITIONS[1],
      rotation: [0, Math.PI, 0],
      material: grayShirt,
      hoverMat: grayStudio,
    },
    {
      slug: "sport",
      geometry: nodes.Shirt_Gray.geometry,
      position: SHIRT_POSITIONS[2],
      rotation: [0, Math.PI, 0],
      material: sportShirt,
      hoverMat: redStudio,
    },
  ]).current;

  const activeStudioMaterial = useStore((state) => state.activeStudioMaterial);
  const setStudioMaterial = useStore((state) => state.setStudioMaterial);
  const currentIndex = useStore((state) => state.currentIndex);

  const scale = useResponsive((state) => state.scale);
  console.log("Scale from store:", scale);

  const meshRefs = useRef<(THREE.Mesh | null)[]>([]);
  const tlRefs = useRef<(GSAPTimeline | null)[]>([]);
  const isMobile = useRef(false);

  const router = useRouter();

  // Prefetch en mount — sin deps innecesarias
  useEffect(() => {
    isMobile.current = window.innerWidth <= 768;
    shirts.forEach(({ slug }) => router.prefetch(`/shirts/${slug}`));
  }, []);

  // Un solo useGSAP para crear las timelines — depende de nodes (estables post-load)
  useGSAP(
    () => {
      meshRefs.current.forEach((mesh, idx) => {
        if (!mesh) return;

        // Limpiar timeline previa si existe
        tlRefs.current[idx]?.kill();

        tlRefs.current[idx] = gsap
          .timeline({ paused: true })
          .to(mesh.rotation, { y: 0, duration: 1, ease: "power2.inOut" })
          .to(
            mesh.scale,
            { x: 1.05, y: 1.05, z: 1.05, duration: 1, ease: "power2.inOut" },
            "<",
          );
      });

      // Cleanup al desmontar
      return () => tlRefs.current.forEach((tl) => tl?.kill());
    },
    { dependencies: [] }, // Solo se ejecuta una vez tras el mount
  );

  // Mobile carousel — usando gsap.to directamente, más eficiente que iterar todos
  useGSAP(() => {
    if (window.innnerWidth > 768) return;

    for (let i = 0; i < meshRefs.current.length; i++) {
      const mesh = meshRefs.current[i];
      if (!mesh) continue;
      switch (currentIndex) {
        case 0:
          gsap.to(mesh.position, { x: mesh.position.x - 0.65 });
          gsap.to(mesh.rotation, { y: 0 });
          gsap.to(meshRefs.current[0]!.position, { z: 0 });
          gsap.to(meshRefs.current[1]!.position, { z: -0.45 });
          setStudioMaterial(whiteStudio);
          break;
        case 1:
          gsap.to(mesh.position, {
            x: shirts[i].position[0],
            z: shirts[i].position[2],
          }); // Volver a posición original
          setStudioMaterial(redStudio);
          break;
        case 2:
          gsap.to(mesh.position, { x: mesh.position.x + 0.65 });
          gsap.to(mesh.rotation, { y: 0 });
          gsap.to(meshRefs.current[2]!.position, { z: 0 });
          gsap.to(meshRefs.current[1]!.position, { z: -0.45 });
          setStudioMaterial(grayStudio);
          break;
      }
    }
  }, [currentIndex]);

  // useCallback para evitar recrear handlers en cada render
  const enterHandler = useCallback(
    (idx: number, hoverMat: typeof defaultStudio) => {
      document.body.style.cursor = "pointer";
      setStudioMaterial(hoverMat);
      tlRefs.current[idx]?.play();
    },
    [],
  );

  const leaveHandler = useCallback((idx: number) => {
    document.body.style.cursor = "auto";
    setStudioMaterial("defaultStudio");
    tlRefs.current[idx]?.reverse();
  }, []);

  const handleClick = useCallback((slug: string) => {
    router.push(`/shirts/${slug}`);
  }, []);

  return (
    <group dispose={null} scale={scale}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Environment.geometry}
        material={activeStudioMaterial}
      />

      {shirts.map((shirt, idx) => (
        <mesh
          ref={(el) => {
            meshRefs.current[idx] = el;
          }}
          key={shirt.slug} // key estable (slug) en lugar de idx
          geometry={shirt.geometry}
          position={shirt.position}
          rotation={shirt.rotation}
          material={shirt.material}
          onPointerEnter={() => enterHandler(idx, shirt.hoverMat)}
          onPointerLeave={() => leaveHandler(idx)}
          onClick={() => handleClick(shirt.slug)}
        />
      ))}

      <mesh
        geometry={nodes.Hitbox.geometry}
        scale={[2.52, 1, 1]}
        visible={false}
        onPointerLeave={() => setStudioMaterial(defaultStudio)}
      />
    </group>
  );
}

useGLTF.preload("/models/main/MainStudio.glb");
export default MainStudioModel;
